# Generated by Django 4.2.26 on 2025-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
