# Generated by Django 4.2.26 on 2025-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0002_alter_passenger_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
