# Generated by Django 4.2.26 on 2025-11-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Management', '0003_alter_passenger_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
